# Copyright 2004 OTP Systems Oy. All rights reserved.

ProductID := JTuxWS

ProductName := JTux Workstation

Samples := SimpleClient StringUtils SimpleAsyncClient DownloadClient SimpleEnqueuer SimpleDequeuer UnsolClient SimpleSubscriber SimpleFML32Client

Docs := JTuxWSInstall JTuxWS_jar

JavaPackages := jtux jtux.holders jtux.atmi jtux.fml32

JavadocFlags := -define WSCLIENT

include ../Makefile.include
