# Copyright 2004 OTP Systems Oy. All rights reserved.

ProductID := JTux

ProductName := JTux

Docs := JTuxInstall JTux_jar JServer JTMS

JavaPackages := jtux jtux.holders jtux.atmi jtux.fml32 jtux.jdbc jtux.jms

Samples := SimpleServer SimpleClient StringUtils SimpleAsyncClient ServerUtils DownloadServer DownloadClient SimpleEnqueuer SimpleDequeuer UnsolServer UnsolClient TimePublisher SimpleSubscriber SimpleFML32Server SimpleFML32Client JDBCService JDBCException JDBCServer JDBCClient JMSService JMSServer JMSClient

include ../Makefile.include
